name: 'Betterer Runner'
description: 'Betterer with custom reporter'
branding:
  icon: 'command'
  color: 'red'
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
outputs:
  time:
    description: 'The message to output'
runs:
  using: 'docker'
  image: 'docker://evilweed88/betterer-github-action:latest'
