name: Betterer ChatOps
description: ChatOps helper for Betterer tool
author: Evilweed <fake-email@asdadasasd.com>
branding:
  icon: book-open
  color: blue
inputs:
  name:
    required: true
    description: Name to greet
  numOctocats:
    description: 'Number of Octocats'
    required: false
    default: '1'
runs:
  using: docker
  image: Dockerfile
