name: betterer-github-action
description: "It's a Betterer runner with custom minimal reporter"
branding:
  icon: "bar-chart"
  color: "red"
runs:
  using: "docker"
  image: "docker://evilweed88/betterer-github-action:latest"
