name: 'Betterer'
description: 'Betterer with custom reporter'
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
outputs:
  time:
    description: 'The message to output'
runs:
  using: 'docker'
  main: 'Dockerfile'
