name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls
      - run: cat package.json
      - name: Test
        uses: ./
        with:
          args: --config /github/workspace/test/.betterer.ts --results /github/workspace/test/.betterer.results --reporter /build/reporter.js /github/workspace/test/test/**/*.ts
      - name: Build
        uses: ./
        with:
          args: yarn build
      - name: Test
        uses: ./
        with:
          args: "--config test/.betterer --results test/.betterer.results --reporter /build/reporter.js"
