name: Test repo action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test that should fail
        id: test-that-should-fail
        continue-on-error: true
        uses: ./
        with:
          args: --config /github/workspace/test/.betterer --results /github/workspace/test/.betterer.results --reporter /build/custom-simple-reporter.js
          PROJECT_NAME: "platform"
          CHATOPS_RESULTS_FILE_UPDATE_COMMAND: 'platform:betterer:update'
          BETTERER_CONFIG_FILE_PATH: "platform/.betterer"
          BETTERER_RESULTS_FILE_NAME: ".betterer.results"
          BETTERER_RESULTS_FILE_PATH: "platform/.betterer.results"
      - run: echo {{ steps.test-that-should-fail.outputs.new_issues_count }}
      - run: echo {{ steps.test-that-should-fail.outputs.fixed_issues_count }}
      - name: Fail if test-that-should-fail passed
        if: steps.test-that-should-fail.outputs.status == 'success'
        run: exit 1
      - name: Test that should pass
        id: test-that-should-pass
        continue-on-error: true
        uses: ./
        with:
          args: --config /github/workspace/test/.betterer --results /github/workspace/test/.betterer-should-pass.results --reporter /build/custom-simple-reporter.js
      - run: echo {{ steps.test-that-should-pass.outputs.new_issues_count }}
      - run: echo {{ steps.test-that-should-pass.outputs.fixed_issues_count }}
      - name: Fail if test-that-should-pass passed
        if: steps.test-that-should-pass.outputs.status == 'failure'
        run: exit 1
