name: Test live docker action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test that should fail
        id: betterer
        uses: Evilweed/betterer-github-action@main
        continue-on-error: true
        with:
          args: --config /github/workspace/test/.betterer --results /github/workspace/test/.betterer.results --reporter /build/custom-simple-reporter.js
          chatops_results_file_update_command: "ts:update"
          betterer_results_file_name: "betterer.results"
      - run: echo {{ steps.betterer.outputs.new_issues_count }}
      - run: echo {{ steps.betterer.outputs.fixed_issues_count }}
